### ISSUE TITLE
No response from OP. Close now.

### ISSUE THREAD

**Issue by ductridev** [sunshine-tech/VietnamProvinces#2]
No response from OP. Close now.

_Originally posted by @hongquan in https://github.com/sunshine-tech/VietnamProvinces/issues/1#issuecomment-680117707_
#1
Sorry about my response take too long time.
Yes, python in my pc is Python 3.6.7

**Comment by hongquan** [comment]
> python in my pc is Python 3.6.7

That can be one of Python installations in your PC. Please provide evidence that the Python in your command

```
python -m dev -i ...
```

is actually Python 3.

Note that, to avoid any problem, please don't change what is instructed in README. The README tells to run `python3 -m dev`, not `python -m dev`.

**Comment by ductridev** [comment]
i have tried python3 -m dev but same error

**Comment by hongquan** [comment]
Please show the screenshot. Also, how about the "Xa_2020-02-25.csv" file in your side? Is it the original file in Git repo or you create it yourself?

**Comment by hongquan** [comment]
Looking again in your error log:

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 172

"charmap" looks unfamiliar. It looks like you are using Windows, whose default encoding is not UTF-8. If so, I cannot support further, because Windows is not my recommended platform for Python. I have no interest to support Windows now (I can change my mind in the future, but not now).
